name: fenwicks_pub
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get:
  date_picker_timeline: ^1.2.3
  fancy_drawer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_rating_bar: ^4.0.0
  staggered_grid_view_flutter: ^0.0.4
  flutter_calendar_carousel: ^2.1.0

  firebase_core: ^1.16.0
  cloud_firestore: ^3.1.14
  firebase_auth: ^3.3.17
  firebase_messaging: ^11.4.1

  intl: ^0.17.0
  cached_network_image: ^3.2.1
  scan: ^1.6.0
  image_picker: ^0.8.5+3
  firebase_storage: ^10.2.16
  flutter_stripe: ^3.0.0
  jiffy: ^5.0.0
  flutter_local_notifications: ^9.5.3+1
  location: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
        - asset: assets/fonts/muli/Muli-Regular.ttf
          weight: 400
        - asset: assets/fonts/muli/Muli-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Black.ttf
          weight: 900

    - family: Open Sans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/open_sans/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/open_sans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/open_sans/OpenSans-ExtraBold.ttf
          weight: 800

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
